### ISSUE TITLE
Ripple effects of list items are stacking on scrolling in mobile

### ISSUE THREAD

**Issue by armaserg** [angular/material2#10082]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Ripple effects of list items shouldn't stack on scrolling in mobile. Ideally, effect even shouldn't be visible when you scroll list. It should be visible only on "tap" (like menu in Google Chrome).

#### What is the current behavior?
Please see video: https://youtu.be/O_H2MG8Torw

#### What are the steps to reproduce?
Is reproducible on https://material.angular.io/
Steps to reproduce:
1) Go to https://material.angular.io/guides ON MOBILE DEVICE using Chrome
2) Click on any link (for example "Getting started")
3) Click Back button on device
4) Try to scroll list quickly
5) You'll see "stack" of ripples

#### What is the use-case or motivation for changing an existing behavior?
It doesn't look good. In Some scenarios it looks horrible :(

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
My site uses angular@5.2.4 and material@5.1.1 but behavior same as on https://material.angular.io/

**Comment by DevVersion** [comment]
Good finding. This just happens because we listen for `touchdown` events, and immediately fade-in a ripple that fades-out after a period of time.

I think it would be the best to not show ripples while scrolling at all. Need to look into it further.

**Comment by armaserg** [comment]
Btw, as I wrote, you can reproduce this only if you come back to the page with ripple list.
So, it looks like something doesn't cleared (event listeners for example) when you leave page.

So, maybe bug has bigger priority?

**Comment by stevenmcountryman** [comment]
There's a similar issue where the ripple causes visible jittering in ngFor lists as well. We have a list of buttons that all use ripple, and when you scroll the list on an iPad or iPhone, the whole page quickly jitters a few pixels up and down. It's very jarring. Hoping for a fix very soon.

**Comment by DevVersion** [comment]
This has been fixed and should be available from the 6.0.0 release of Material

**Comment by armaserg** [comment]
It is still reproducible with same steps...
For my site this fix is very important. As in many cases it looks ugly :(

**Comment by stewwan** [comment]
same here

**Comment by stewwan** [comment]
I had the same issue here. In my case I realized that the (tap) event was messing up some css properties like `touch` etc. so I ended up by using the (click) event in areas that need to scroll

**Comment by stewwan** [comment]
I had the same issue here. In my case I realized that the (tap) event was messing up some css properties like touch etc. so I ended up by using the (click) event instead, in areas that need to scroll
