### ISSUE TITLE
New Angular Material schematics directory appears in project's root folder

### ISSUE THREAD

**Issue by Chan4077** [angular/material2#11198]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
There seems to be a new Angular Material schematics directory in my project's root folder after updating to `6.0.0`. This directory shouldn't exist.

#### What is the current behavior?
The directory exists after updating.

Note the `angular_material_schematics_cDdroP` directory in the output of `ls`:
![screen shot 2018-05-07 at 18 07 24](https://user-images.githubusercontent.com/20047125/39696830-891a89b6-5221-11e8-9e43-cd1f4ac94755.jpg)

#### What are the steps to reproduce?
1. Have an existing project.
2. Update that project to `6.0.0`.

#### What is the use-case or motivation for changing an existing behavior?
NIL

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular 6
- Angular Material 6
- All operating systems
- TypeScript `2.7.2`
- All browsers

#### Is there anything else we should know?
P.S. The directory seems to be ignored when entering `git status`..
P.P.S. Someone else also asked the same thing about this on StackOverflow: https://stackoverflow.com/questions/50178633/angular-material-schematics-folder-after-upgrade-to-angular-6

**Comment by jelbourn** [comment]
@amcdnl could you take a look? The update schematic is supposed to create a temp directory, it's weird that it would do it in the project directory.

**Comment by julianobrasil** [comment]
@Chan4077, maybe this `@angular/cli` issue is the root cause: https://github.com/angular/angular-cli/issues/10672

If so, installing `@angular/cli@6.0.1` should fix it.

**Comment by Chan4077** [comment]
@julianobrasil Just tried what you suggested in updating my other app to Angular v6, but I still encountered the error, even after updating the global and local Angular CLI to `6.0.1`.

# Before updating Angular Material to `6.0.1` from `6.0.0`

While updating, I encountered this error after the Angular CLI logged adding the Angular Material schematics:
```bash
TypeError: directiveMetadata.properties is not iterable
    at SwitchStylesheetAtributeSelectorsWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetAtributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetAtributeSelectorsWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetAtributeSelectorsWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetAtributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchStylesheetCssNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetCssNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetCssNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetCssNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetCssNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchStylesheetElementSelectorsWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetElementSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetElementSelectorsWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetElementSelectorsWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetElementSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchStylesheetInputNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetInputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetInputNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetInputNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetInputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchStylesheetOutputNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetOutputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetOutputNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetOutputNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetOutputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateAttributeSelectorsWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateAttributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateAttributeSelectorsWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateAttributeSelectorsWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateAttributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateCaaNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateCaaNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateCaaNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateCaaNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateCaaNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateElementSelectorsWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateElementSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateElementSelectorsWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateElementSelectorsWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateElementSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateExportAsNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateExportAsNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateExportAsNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateExportAsNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateExportAsNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateInputNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateInputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateInputNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateInputNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateInputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchTemplateOutputNamesWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchTemplateOutputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchTemplateOutputNamesWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchTemplateOutputNamesWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchTemplateOutputNamesWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'flags' of undefined
    at Object.getBaseTypes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:28740:38)
    at CheckInheritanceWalker.visitClassDeclaration (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/rules/checkInheritanceRule.js:20:49)
    at CheckInheritanceWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:314:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13479:24)
    at CheckInheritanceWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at CheckInheritanceWalker.SyntaxWalker.visitSourceFile (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:228:14)
    at CheckInheritanceWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:482:22)
    at CheckInheritanceWalker.SyntaxWalker.walk (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at CheckTemplateMiscWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at CheckTemplateMiscWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at CheckTemplateMiscWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at CheckTemplateMiscWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at CheckTemplateMiscWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at SwitchStylesheetAtributeSelectorsWalker._visitDirectiveCallExpression (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:40:50)
    at SwitchStylesheetAtributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:30:22)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13263:24)
    at Object.forEachChild (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13544:24)
    at SwitchStylesheetAtributeSelectorsWalker.SyntaxWalker.walkChildren (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at SwitchStylesheetAtributeSelectorsWalker.SyntaxWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:530:22)
    at SwitchStylesheetAtributeSelectorsWalker.visitNode (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/angular_material_schematics-YOsO24/update/tslint/component-walker.js:33:15)
    at /Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/edricchan/Desktop/Projects/rss-reader/rss-reader-web/node_modules/typescript/lib/typescript.js:13272:30)
```

# After updating manually to Angular Material `6.0.1`
I manually updated to Angular Material `6.0.1` and ran `ng update @angular/material`. However, it was the same result. The schematics directory still existed.

Here's the result from `ls -hFl`:
```bash
$ ls -hFl
total 1048
-rw-r--r--    1 edricchan  staff   1.0K Oct 22  2017 LICENSE
-rw-r--r--    1 edricchan  staff   709B Dec 12 12:05 README.md
-rw-r--r--    1 edricchan  staff   4.4K May 13 00:33 angular.json
drwx------    8 edricchan  staff   256B May 13 00:39 angular_material_schematics-YOsO24/
drwxr-xr-x@   5 edricchan  staff   160B Oct 19  2017 docs/
drwxr-xr-x    5 edricchan  staff   160B Jul 27  2017 e2e/
-rw-r--r--    1 edricchan  staff   835B Nov  3  2017 gulpfile.js
-rw-r--r--    1 edricchan  staff   1.2K May 13 00:33 karma.conf.js
drwxr-xr-x  892 edricchan  staff    28K May 13 00:41 node_modules/
-rw-r--r--    1 edricchan  staff   481K May 13 00:41 package-lock.json
-rw-r--r--    1 edricchan  staff   2.2K May 13 00:41 package.json
-rw-r--r--    1 edricchan  staff   796B Jul 27  2017 protractor.conf.js
drwxr-xr-x    2 edricchan  staff    64B Oct 19  2017 scripts/
drwxr-xr-x   17 edricchan  staff   544B Mar 19 10:10 src/
drwxr-xr-x    4 edricchan  staff   128B Nov 12 19:26 tools/
-rw-r--r--    1 edricchan  staff   384B Jul 27  2017 tsconfig.json
-rw-r--r--    1 edricchan  staff   2.2K May 13 00:33 tslint.json
```

**Comment by Springrbua** [comment]
I am facing the same issue as @Chan4077 
For the update, I followed the steps provided [here](https://stackoverflow.com/a/50189598/3182091).

After updating the CLI (v6.0.1) and Angular Core, I executed `ng update @angular/material`.
This first updates @angular/material and @angular/cdk to version 6.0.1.
Then it creates all the schematics. After that, I get a lot of errors (`TypeError: directiveMetadata.properties is not iterable`) and the command seems to get stuck.
I guess, thats why the schematics are not cleaned up, as the command does not finish it's execution.

**Comment by byronsanchez** [comment]
I am facing the same issue. Wondering if there's anything I should do or maybe I can safely ignore it.

**Comment by inorganik** [comment]
FWIW, `angular_material_schematics-* ` folder(s) can be safely deleted. Still, the issue remains that they were meant to be temporary, but not deleted in the `ng update` process.

**Comment by Springrbua** [comment]
@inorganik I don't worry that much about the files, but the error, which prevents their deletion.
The problem IMHO is, that if the error oocures before all schematics did their work, the upgrade from Material v5 to v6 would be incomplete.

**Comment by byronsanchez** [comment]
Same, I had the stacktrace error that @Chan4077 reported (`TypeError: directiveMetadata.properties is not iterable`). So whatever angular material was doing with schematics looks like it was interrupted and thus I had the same concerns as @Springrbua that something about my angular material schematics were broken. TBH, don't know much about the schematics part yet. I ended up removing node_modules and just running npm install.

In any case, looks like my project is building locally with no problems. So I'm just gonna cross my fingers and hope that this schematics error wasn't *that* important.

**Comment by juristr** [comment]
> The problem IMHO is, that if the error oocures before all schematics did their work, the upgrade from Material v5 to v6 would be incomplete.

Yep, agree. In my case I end up with material deps like

```
"@angular/cdk": ">=5 <6",
"@angular/material": ">=5 <6",
```

..which doesn't seem right tbh

**Comment by Chan4077** [comment]
@jelbourn According to the NodeJS docs, `fs#mkdtempSync` accepts two parameters, a `prefix` of type `string` and an optional `options` of type `Object` or `string`. The `prefix` parameter will be what and where the temporary folder will get created and it looks to me like it will get created at the project's directory since the schematic is executed at the project level:

https://github.com/angular/material2/blob/abc3d38c57146443c848d5ba26fd2fab8ca185d6/src/lib/schematics/update/update.ts#L12

See the [documentation for `mkdtempSync`](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback) for more info.

As for the deletion of the folder, I don't really understand why everything in the temporary folder except the folders gets deleted. Could it be because of these lines that cause the issue?

https://github.com/angular/material2/blob/abc3d38c57146443c848d5ba26fd2fab8ca185d6/src/lib/schematics/update/update.ts#L81-L86

**Comment by Springrbua** [comment]
I tryed to upgrade my project again and I noticed, that it changed all `mat-input-container` in the *.scss-Files to `mat-form-field`. However the *.html-Files are still the same, so I think the schematics did not complete as they should.

**Comment by amcdnl** [comment]
Closing per merge. @Springrbua - Might want to log a separate issue with more details for that.

**Comment by Springrbua** [comment]
@amcdnl I guess, the problem I noticed has to do with the error in this issue. So it is probably solved too. However, I can't test it anymore, since I already upgraded the project manually.
