### ISSUE TITLE
md-input (type=number) possible bug: Restore Placeholder on empty value

### ISSUE THREAD

**Issue by MoxxNull** [angular/material2#1127]
#### Bug, feature request, or proposal:

Bug (maybe)
#### What is the expected behavior?

If I user an md-input with type number and delete the input value, the placeholder should go back to it's initial place (= Inside Input box) , like placeholder get's restored in a plain html input box.
#### What is the current behavior?

Upon erasing the field, console prints 

```
"The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?"
```

The field is empty, but the placeholder remains ontop of the box.
#### What are the steps to reproduce?

See [Plunker](http://plnkr.co/edit/afWwM0KZOF1VvYIa3jlG?p=preview)
#### Which versions of Angular, Material, OS, browsers are affected?

Current Angular rc5 / Material alpha.7
#### Is there anything else we should know?

Yes, I like your work :) Thank you very much.

**Comment by Mario-Eis** [comment]
The problem seems to be an "" (empty string) when a contained value is deleted. This also affects form validation as a required field stays valid although its "empty".

**Comment by pearman** [comment]
There also seems to be an issue when the type is "number." If the user inputs a decimal number starting with "." the text box is cleared and the error bellow is triggered. However, it only seems to happen on the first try.
`
"The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?"`

**Comment by MoxxNull** [comment]
And same goes for negative numbers. The first input of a leading "-" produces the same error. The second try works as it should.

**Comment by mmalerba** [comment]
fixed for `md-input-container` which will replace `md-input`

**Comment by buu700** [comment]
I'm still seeing this behavior with a `mat-form-field > input[type="number"]`. Doesn't seem to break anything, so not that big a deal, but is this expected?

**Comment by mmalerba** [comment]
@buu700 it seems fine to me: https://stackblitz.com/edit/angular-material2-issue-ktof1p?file=app/app.component.html

**Comment by buu700** [comment]
Oh, sorry, you're right; I should've tested that first. Thanks!

(The actual problem is that `[(ngModel)]='aNumber'` doesn't work as I expected it to, so as a workaround we're doing `[ngModel]='aNumber' (ngModelChange)='aNumber = parseInt($event)'`, which as-is doesn't take into account that parsing an empty string returns `NaN`.)
