### ISSUE TITLE
Building issues with Angular2.rc6

### ISSUE THREAD

**Issue by eromero90** [angular/material2#1186]
#### Bug, feature request, or proposal:
I'm trying to run my project after updating my project to Angular2,rc6 and Material2 has building issues.

I'm using webpack, Angular2.rc6 and Material2 2.0.0-alpha.8-1

Here you can find the error:

```
ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,27): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,27): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,29): error TS2300: Duplicate identifier 'number'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,29): error TS2300: Duplicate identifier 'number'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,14): error TS2304: Cannot find name '_ariaValueMin'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(17,29): error TS7008: Member 'number' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,14): error TS2304: Cannot find name '_ariaValueMax'.

ERROR in C:\myProject\node_modules\@angular2-material\progress-circle\progress-circle.d.ts
(18,29): error TS7008: Member 'number' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(28,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(28,22): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(29,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(29,28): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(28,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(29,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(28,14): error TS2304: Cannot find name 'tabIndex'.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(28,24): error TS7008: Member 'number' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(29,14): error TS2304: Cannot find name 'isAriaDisabled'.

ERROR in C:\myProject\node_modules\@angular2-material\button\button.d.ts
(29,30): error TS7008: Member 'string' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,24): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,24): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,14): error TS2304: Cannot find name 'elementRef'.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(12,26): error TS7008: Member 'ElementRef' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,14): error TS2304: Cannot find name 'overlayRef'.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\overlay-directives.d.ts
(24,26): error TS7008: Member 'OverlayRef' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,23): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,47): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,14): error TS2304: Cannot find name 'positions'.

ERROR in C:\myProject\node_modules\@angular2-material\core\overlay\position\connected-position-strategy.d.ts
(24,25): error TS7008: Member 'ConnectionPositionPair' implicitly has an 'any[]' type.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(14,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(14,24): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(53,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(53,20): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(14,14): error TS2304: Cannot find name 'isAttached'.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(14,26): error TS7008: Member 'boolean' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(53,14): error TS2304: Cannot find name 'origin'.

ERROR in C:\myProject\node_modules\@angular2-material\core\portal\portal.d.ts
(53,22): error TS7008: Member 'ElementRef' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,21): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,19): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(52,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(52,28): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(53,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(53,21): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,20): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,44): error TS1005: '(' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,21): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,45): error TS1005: '(' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(85,14): error TS1005: '=' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(85,20): error TS1005: ';' expected.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,23): error TS2300: Duplicate identifier 'boolean'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,21): error TS2300: Duplicate identifier 'boolean'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(52,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(53,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(73,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(85,5): error TS2300: Duplicate identifier 'readonly'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,14): error TS2304: Cannot find name 'focused'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(50,23): error TS7008: Member 'boolean' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,14): error TS2304: Cannot find name 'empty'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(51,21): error TS7008: Member 'boolean' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(52,14): error TS2304: Cannot find name 'characterCount'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(52,30): error TS7008: Member 'number' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(53,14): error TS2304: Cannot find name 'inputId'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(53,23): error TS7008: Member 'string' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,14): error TS2304: Cannot find name 'onBlur'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(82,22): error TS7010: 'Observable', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,14): error TS2304: Cannot find name 'onFocus'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(83,23): error TS7010: 'Observable', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(85,14): error TS2304: Cannot find name '_align'.

ERROR in C:\myProject\node_modules\@angular2-material\input\input.d.ts
(85,22): error TS7008: Member 'any' implicitly has an 'any' type.

ERROR in C:\myProject\node_modules\@angular\forms\src\form_providers.d.ts
(13,38): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\form_providers.d.ts
(18,47): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives\select_multiple_control_value_accessor.d.ts
(12,18): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives.d.ts
(26,46): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives.d.ts
(27,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives.d.ts
(28,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives.d.ts
(46,39): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in C:\myProject\node_modules\@angular\forms\src\directives.d.ts
(50,48): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
```

**Comment by DevVersion** [comment]
What TypeScript version do you use?

I assume you are not using TypeScript@2.0.0, which means that your transpiler is not able to parse those definitions properly.

**Comment by eromero90** [comment]
Hi @DevVersion, I'm using TypeScript@1.8.10

**Comment by DevVersion** [comment]
@eromero90 Cool thx - I'm pretty sure that this issue is related to your TypeScript version, because the Material 2 typings are based on `Typescript@2.0.0` (try updating to v2)

---
Also we should make sure that this is documented in the `Readme.MD`

**Comment by eromero90** [comment]
@DevVersion Thanks! I have updated TypeScript and it's working now.  Now I have issues with @angular/forms but I'm going to read more about the issue. Thanks againg.

**Comment by kara** [comment]
Looks like this issue is resolved. Thanks @DevVersion for the suggested fix.

**Comment by agyrafa** [comment]
I'm using 

``"typescript": "^2.0.2"``

And still getting this error
