### ISSUE TITLE
routerLink is not working for mat-button-toggle in 6.3.1

### ISSUE THREAD

**Issue by zijianhuang** [angular/material2#11944]
#### Bug

```html
            <mat-button-toggle-group #group="matButtonToggleGroup" [value]="currentModuleName">
                <mat-button-toggle routerLink="/ml_appointments" value="appointments">
                    <i fxHide.md class="material-icons">event</i>
                    <span fxHide.sm fxHide.xs>Appointments</span>
                </mat-button-toggle>
                <mat-button-toggle routerLink="/tasks" value="tasks">
                    <i fxHide.md class="material-icons">donut_large</i>
                    <span fxHide.sm fxHide.xs>Tasks</span>
                </mat-button-toggle>
```

No routing happens when the toggle button is clicked.

#### What is the expected behavior?

Routing should happen according to the definitions in the routing module. The same code is working well in 6.3.0 and all previous releases. 

#### What is the current behavior?

No routing happens.

#### Is there anything else we should know?

While I could do the routing in the TS codes, however for this scenario I would prefer to have the routing declared in the HTML template.

**Comment by josephperrott** [comment]
Closing as this was fixed by #11951

**Comment by dcolakchile** [comment]
This still does not work. Have latest version of everything. routerLink within material button does not work.
