### ISSUE TITLE
Input type date overlaps with placeholder

### ISSUE THREAD

**Issue by tomascharad** [angular/material2#1238]
Input type date overlaps with placeholder

<img width="163" alt="screen shot 2016-09-14 at 11 36 34 am" src="https://cloud.githubusercontent.com/assets/1534092/18516475/8e70bb3c-7a6f-11e6-93e6-cef30c4e17c2.png">

```html
<md-input placeholder="Fecha de nacimiento" type="date" [value]="userDetail.get('birthdate')" (input)="actions.inputChanged($event, 'birthdate')"></md-input>
```

"@angular/common": "^2.0.0-rc.6",
"@angular/compiler": "^2.0.0-rc.6",
"@angular/core": "^2.0.0-rc.6",
"@angular/forms": "^2.0.0-rc.6",
"@angular/http": "^2.0.0-rc.6",
"@angular/platform-browser": "^2.0.0-rc.6",
"@angular/platform-browser-dynamic": "^2.0.0-rc.6",
"@angular/router": "^3.0.0-rc.2",
"@angular/router-deprecated": "2.0.0-rc.2",
"@angular2-material/button": "^2.0.0-alpha.8-1",
"@angular2-material/card": "^2.0.0-alpha.8-1",
"@angular2-material/checkbox": "^2.0.0-alpha.8-1",
"@angular2-material/core": "^2.0.0-alpha.8-1",
"@angular2-material/input": "^2.0.0-alpha.8-1",
"@angular2-material/list": "^2.0.0-alpha.8-1",
"@angular2-material/radio": "^2.0.0-alpha.8-1",

**Comment by danielgek** [comment]
@tomascharad in next release will be fixed, see this [commit](https://github.com/angular/material2/commit/fe2b493fd887a883b5e54dcf0769df90df51375c)

**Comment by vinagreti** [comment]
Why not use some CSS to hide the HTML placeholder when the input is not focused?
When you treat the input as not empty your placeholders appear different because in empty date input they are always on top of the field and in any other input they are inside.
Is it a workaround until datepicker is ready?

About the CSS approach, should be something like:

    /*///////////////////////////////////////*/
    /* Remove date default html5 placeholder */
    /*///////////////////////////////////////*/
    .no-datetime-placeholder input::-webkit-datetime-edit{ color: transparent; }

    /* Include this to make it visible when input is clicked */
    .no-datetime-placeholder input:focus::-webkit-datetime-edit{ color: #000; }

**Comment by kara** [comment]
This should be fixed in master, so closing.

**Comment by no-more** [comment]
Hi,

I'm using alpha.9-2, it's working for date input, but not for time input As I haven't found any thing about time input I think the issue is still in master.

Thanks.

**Comment by TrevorBroderick1** [comment]
I agree with @no-more .

This is fixed for type `date` but still occurs for type `datetime-local`.

Can we re-open this issue @kara ?
