### ISSUE TITLE
bug:(@angular/cdk/drag-drop): Cannot read property 'clientRect' of undefined

### ISSUE THREAD

**Issue by kanidjar** [angular/material2#13077]
#### Bug, feature request, or proposal:

BUG: when drag-dropping an item between two connected dropzone, an error occurs randomly

See video and image below

https://streamable.com/nuudt

![error](https://user-images.githubusercontent.com/12607242/45362000-f51f5b80-b5d3-11e8-8923-bc91b3c36ece.jpg)

#### What is the expected behavior?

No error should occur.

#### What is the current behavior?

An error occurs randomly as soon as an item enters in the dropzone. The (dropped) event happens anyway.

#### What are the steps to reproduce?

Classic connected dropzones.

My dropzones are not in the same component.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

"@angular/cdk": "^7.0.0-beta.0"
"@angular/material": "^6.4.7"
"@angular/core": "^6.1.6",

#### Is there anything else we should know?

The error is located in drag-drop.es5.js.CdkDrop._sortItem (drag-drop.es5.js:1436)

```javascript
var currentPosition = siblings[currentIndex].clientRect;
```

**Comment by crisbeto** [comment]
It's hard to tell what's going on based on the video. Based on the stack trace, it looks like a `CdkDrag` somehow ended up in the wrong container, but I can't think of any obvious place where it could happen. @kanidjar would you be able to put together a simplified example that breaks?

**Comment by kanidjar** [comment]
@crisbeto 

here it is : https://stackblitz.com/edit/angular-uhe5x7

Try to drop a same item twice in the red zone.

**Comment by crisbeto** [comment]
Thanks for the reproduction @kanidjar. It looks like the issue was fixed in master already.

**Comment by kanidjar** [comment]
Nice, thank you @crisbeto

**Comment by dakotamaker** [comment]
@crisbeto what was the fix exactly? I'm still seeing this issue and I am on the newest version of the cdk

**Comment by antonpegov** [comment]
I'm getting this error when applying [cdkDropList] directive it the parent component and [cdkDragData] in  it's childrens. When everything in the one component, then no errors.

**Comment by birjitningomba** [comment]
@crisbeto I am trying to sort or dragdrop dynamically generated components. The container has the cdkDropList directive while the dynamically components has the cdkDrag directive and I would expect it works, It is simply not working.

**Comment by birjitningomba** [comment]
The drag & drop is a great feature, In my opinion it should be not only with simple list that we can drag and drop but also components and more specific to dynamic components. I am sure the usage of dynamic components may be limited scope but this is where Angular is helping new developers like us achive a lot of things quickly and easily. I do not understand the priority of the bugs but to me this bug should be raised to a higher priority. @crisbeto please comment.

**Comment by millerlight** [comment]
same problems here with mat-table as cdkDropList and mat-row inside as cdkDrag

this means that the new drag&drop api in angular7 is not usable with mat-tables which is sad, because i need this features...

**Comment by millerlight** [comment]
btw. only dragging of mat-tables works fine....

**Comment by cantastage** [comment]
Hello. Same problem with "@angular/cdk": "^7.1.1". I have a component with two connected cdkDropList. One list is filled with dynamically generated components that contain the cdkDrag directive in the template. When I try to drag one of these elements the error appears.

**Comment by davidecavestro** [comment]
I reproduce it adding D&D to reorder reactive form controls, dynamically added within a single angular component.
@JesseZomer or @cantastage could you please elaborate on the workaround you've found?

**Comment by jheyl** [comment]
Hey guys, 
I stumbled upon this thread because I had the exact same the Problem when I used the cdkDrag Directive in a span inside a [ngb-container](https://ng-bootstrap.github.io/#/components/collapse/api). 

Using the exact same code inside a <ul>-element works without any problems.

**Comment by amumm** [comment]
I am experiencing the same issued. I need to be able to call the (cdkDragDropped) event within the child component, but this error makes it so the cdkDropList does not recognize the cdkDrop when in separate components.

**Comment by waniashik** [comment]
I am struggling with the same issue, has this issue been fixed?

**Comment by TeXnicians** [comment]
FYI, it seems that I added `opacity: 1` to the draggable items and the error disappears. Not sure why.

**Comment by andyrue** [comment]
I added a cdkDragHandle to an element inside my draggable component and I no longer got this error.

**Comment by xdevnull** [comment]
Any fix?

**Comment by ibenjelloun** [comment]
I'm reproducing this error on the stackblitz example from [angular.io](https://material.angular.io/cdk/drag-drop/overview#reordering-lists) : 
https://stackblitz.com/angular/dgxqejknvgg?file=app%2Fcdk-drag-drop-sorting-example.ts

![cdk-drag-drop-clientRectOfUndefined](https://user-images.githubusercontent.com/1528304/58091609-56b7b100-7bca-11e9-9839-ee422953495d.gif)

**Comment by AlyRadwan2020** [comment]
@kanidjar 
look for this 
`<div class="container" *ngIf="loading" cdkDropListGroup>

  <div *ngFor="let workorder of workorders" class="card text-dark bg-light">
    <div class="card-header bg-dark text-center text-light">
      <h4>{{workorder.zone}}</h4>
    </div>
    <div  class="card-body">
      <div class="example-container" *ngFor="let zoneDay of workorder.zoneDays">
        <h2>{{zoneDay.name}}</h2>

        <div cdkDropList [cdkDropListData]="zoneDay.orders" class="example-list" (cdkDropListDropped)="drop($event)">
          <div class="example-box" *ngFor="let order of zoneDay.orders" cdkDrag>{{order.hashcode}}
            {{order.pickupaddress}}</div>
          <button class="btn btn-primary" (click)="approveWorkorder(zoneDay)">Approve</button>
        </div>
      </div>
    </div>

  </div>




</div>
`

**Comment by kflo** [comment]
**bump** ...
