### ISSUE TITLE
Error: ctorParameters.map is not a function at the start of app, when importing MatTableModule.

### ISSUE THREAD

**Issue by Veetaha** [angular/material2#14100]
#### What is the expected behavior?

It must simply run with no errors.

#### What is the current behavior?

`Uncaught TypeError: ctorParameters.map is not a function` is thrown at the start of the web-application which is caused by importing `MatTableModule`

#### What are the steps to reproduce?
Unfortunately I can't reproduce this issue via StackBlitz, but you can clone [a repository with the minimum project that has this error](https://github.com/Veetaha/angular-material-mattable-issue), run `npm i && ng serve` and see this error in your browser console at `localhost:4200`.

#### What is the use-case or motivation for changing an existing behavior?
My project doesn't run with this bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.0.3
Material: 7.0.3
OS: Ubuntu 18.04.1 LTS
TypeScript: 3.1.6

#### Is there anything else we should know?
This error happens **ONLY** when importing *MatTableModule*. Other modules, like `MatCardModule` or `MatMenuModule` work well.
If you inspect the issue via Chrome's debugger you will see that `ctorParameters` is not an array but a function originated from `table.js` file (see attached gif for more info). [These answers from stackoverflow](https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl) for an analogous issue don't save the day as they propose just to update my dependencies, but they are all up to date.
Please, see [a repository with the minimum project that has this error](https://github.com/Veetaha/angular-material-mattable-issue) for more info.

![issue](https://user-images.githubusercontent.com/36276403/48360371-c55e0400-e6a7-11e8-9643-559fd20bcf0a.gif).

**Comment by DevVersion** [comment]
This is already fixed with #14066. Thanks for your issue.

**Comment by svstartuplab** [comment]
This issue is NOT FIXED.  Please reopen.  I'm having the same problem with 7.1.0 and TS 3.1.6.  I imported a dozen AM modules into a xxx.module.ts and clean cli component.  Only the table module crashes the lazy loaded module.  None of the modules are used in the component so something is happening on import.  Other parts of my app that don't have the table are fine.   I can continue dev for now.

**Comment by DevVersion** [comment]
Thanks for your feedback. Please see the PR description of #14066 

> With two commits (2adced1 and a22a9fa), we recently tried to add a workaround for an Angular bug that causes Angular Material to not work w/ ES2015.

> The workaround technically worked but had to be partially reverted because Google Closure compiler was no longer able to remove unused classes (due to a function with side-effects that modified the actual component metadata).

> Since the workaround (in the state it is right now) is not helping at all and a fix will land with Angular v7.1.0 (angular/angular@95743e3), we are removing the workaround completely.

**Comment by svstartuplab** [comment]
I read that but don't understand what to do.  I have no idea what a closure compiler is.  Roll back to v6 somehow?  Forget using AM table?

**Comment by DevVersion** [comment]
As I've mentioned in #14066. Can you confirm that you use Angular Material v7.1.0 **and** Angular v7.1.0? Also please respond in #14066, so we don't have two conversations at the same time.

**Comment by svstartuplab** [comment]
Sure, let's move to 14066.  As mentioned though I'm using 7.1.0 and the latest TS, if that matters.
