### ISSUE TITLE
md-slider cannot be disabled

### ISSUE THREAD

**Issue by bogdandorca** [angular/material2#1676]
#### Bug, feature request, or proposal:
The md-slider-toggle cannot be set as disabled.

#### What is the expected behavior?
When I set the "disabled" property, I want the md-slider to be disabled so that the user cannot change it's state.

#### What is the current behavior?
When the "disabled" property is set, the user cannot click on the slider.
They can still manually drag the slider in order to change it's value.

#### What are the steps to reproduce?
Set the md-slider-toggle as disabled ([disabled]="true").
Go on the page and manually drag the slider to the other state.
The state changes.

http://plnkr.co/edit/7go4puQo8iVGfpjv2uxv

**Comment by DevVersion** [comment]
This has been fixed within `master` with SHA https://github.com/angular/material2/commit/89083660964662efcabe814702fe61f0fad5bc37

**Comment by nicolae536** [comment]
In 2.0.0-alpha.9-3 ? cause that's the package that we use

**Comment by bogdandorca** [comment]
@DevVersion The current version is alpha 9-3. In this version the issue still reproduces.
Please see the plunkr attached to the initial request. That uses the latest version and the issues is still there.

Could you please advise regarding this? What version of Material should I upgrade to in order for this to be fixed?

Thanks! :)

**Comment by DevVersion** [comment]
@nicolae536 @bogdandorca From what I see it's not released yet, so there might be no easy way to use it right now (other than using `master`)

**Comment by bogdandorca** [comment]
@DevVersion Do you have any idea when it will be released?

Thanks a lot for your help!

**Comment by DevVersion** [comment]
@bogdandorca Sorry I have no idea when it's planned to do another release.
