### ISSUE TITLE
md-button looks 3 different ways depending on where/how it's used 

### ISSUE THREAD

**Issue by colemickens** [angular/material2#2030]
http://plnkr.co/edit/uPVX2MsPhbfkj5DUTAeI?

There are three buttons in that plnkr and I expected them to all look the same, but they don't.

Seems like a bug possibly?

**Comment by fxck** [comment]
https://github.com/angular/material2/issues/1946

**Comment by jelbourn** [comment]
Should be fixed in alpha.11

**Comment by colemickens** [comment]
It doesn't look right in the Plunkr and I think it points to latest. It now looks the same as it does in my project where I've bumped to alpha.11. Am I using it incorrectly or is there still a problem?

**Comment by fxck** [comment]
Plunker is still alpha 10

**Comment by colemickens** [comment]
Plunkr seems to link to unversioned unpkg links which default to latest. Further more, it looks the same as it does on my devbox after bumping to alpha.11.

It actually looked more accurate under alpha.10. This is definitely not fixed. @jelbourn  can you please reopen?

**Comment by colemickens** [comment]
Ping, this issue isn't fixed, please reopen or advise. thanks.

**Comment by colemickens** [comment]
Looks like it might be close but the text is rendered as white (on a white bg) instead of black text on a white button as it renders in other places beside the header.

**Comment by jelbourn** [comment]
The button uses `currentColor` for the text. Inside of your toolbar it's white.

**Comment by colemickens** [comment]
I see. If the output in plunkr is expected then I will take this as "user error" and figure it out, thanks for the pointer!
