### ISSUE TITLE
Anuglar Material 2 doesn't work in Electron

### ISSUE THREAD

**Issue by DevWurm** [angular/material2#2398]
#### Bug, feature request, or proposal:
When including the Material module in an Electron App, the App crashes. 

#### What is the expected behavior?
It should include the module and show the material components.

#### What is the current behavior?
The app crashes when loading the module. It shows the following error:
```
bootstrap 5765295…:111
Uncaught TypeError: Cannot redefine property: MaterialModule
__webpack_require__.d @ bootstrap 5765295…:111
(anonymous function) @ icon.js:264
__webpack_require__ @ bootstrap 5765295…:52
(anonymous function) @ index.js:4
__webpack_require__ @ bootstrap 5765295…:52
(anonymous function) @ app.module.ts:22
__webpack_require__ @ bootstrap 5765295…:52
(anonymous function) @ main.bundle.js:53731
__webpack_require__ @ bootstrap 5765295…:52
(anonymous function) @ main.bundle.js:83174
__webpack_require__ @ bootstrap 5765295…:52
webpackJsonpCallback @ bootstrap 5765295…:23
(anonymous function) @ main.bundle.js:1

#### What are the steps to reproduce?
Clone [this](https://github.com/DevWurm/hello-electron) small sample project and run `npm install`. Install the `@angular/material` package in a version `>= beta.0` and import it in `src/app.module.ts` and add a material component to `arc/app.component.html`. Set the environment `NODE_ENV` to `development` to easily see the error messages. Run the app with `npm run start`. The error occurs in the console. 

#### What is the use-case or motivation for changing an existing behavior?
I want to use Angular Material in an Electron App

#### Which versions of Angular, Material, OS, browsers are affected?
The bug occurs since version `2.0.0-beta.0`. It works flawlessly until `2.0.0-alpha.11`. I use the following other packages:
```json
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/material": "^2.0.0-beta.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.19-3",
    "codelyzer": "1.0.0-beta.1",
    "concurrently": "^3.1.0",
    "copy-webpack-plugin": "^4.0.1",
    "cpx": "^1.5.0",
    "electron": "^1.4.12",
    "electron-packager": "^8.4.0",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-electron": "^5.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
```

#### Is there anything else we should know?
It may be related to [this issue](https://github.com/angular/universal-starter/issues/266).

**Comment by dolanmiu** [comment]
It works for me on version 2.0.0-beta.1

Perhaps it is fixed.

Can be closed?

**Comment by DevWurm** [comment]
I can't confirm this :(
The issue still appears in my sample project. You can find the code, where the error occurs in [the `issue-1` branch of DevWurm/hello-electron](https://github.com/DevWurm/hello-electron/tree/issue-1).
After running `npm install` you can run `NODE_ENV=development npm run start` to see the error.

**Comment by alexcharrier** [comment]
The issue still appears with the latest version of angular-cli (1.0.0-rc.0) and @angular/material (2.0.0-beta.2).
No error is written in the console but a basic material input doesn't work.

Does anyone have a solution or is working on this problem?

**Comment by DevWurm** [comment]
I tried it recently and it worked :)
