### ISSUE TITLE
Updating to beta broke my app

### ISSUE THREAD

**Issue by davidmontgom** [angular/material2#2468]
Updating to beta broke my app.  Why?  How do I resolve?  =

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (snack-bar-container.js:4)
    at snack-bar-container.js:28
    at Object.<anonymous> (snack-bar-container.js:122)
    at __webpack_require__ (bootstrap 1e1cb11…:52)
    at Object.<anonymous> (snack-bar-ref.js:70)
    at __webpack_require__ (bootstrap 1e1cb11…:52)
    at Object.<anonymous> (menu.js:40)
    at __webpack_require__ (bootstrap 1e1cb11…:52)
    at Object.<anonymous> (icon.js:264)
    at __webpack_require__ (bootstrap 1e1cb11…:52)
__extends @ snack-bar-container.js:4
(anonymous) @ snack-bar-container.js:28
(anonymous) @ snack-bar-container.js:122
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ snack-bar-ref.js:70
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ menu.js:40
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ icon.js:264
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ index.js:4
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ git-host.enum.ts:4
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ src async:7
__webpack_require__ @ bootstrap 1e1cb11…:52
(anonymous) @ zone.js:1327
__webpack_require__ @ bootstrap 1e1cb11…:52
webpackJsonpCallback @ bootstrap 1e1cb11…:23
(anonymous) @ main.bundle.js:1

**Comment by spock123** [comment]
Are you using webpack standaloe, ie. not Angular-cli?

if so the issue is with Webpack and has been reported

**Comment by fabriziodebortoli** [comment]
I'm the same issue with 
angular "2.4.1"
material 2.0.0.beta.1
angular-cli: 1.0.0-beta.15

Trying with webpack: 2.2.0-rc.3 is bad

I've also these warnings:
./~/@angular/material/module.js
64:4 export 'ProjectionModule' was not found in './core/index'
Error: export 'ProjectionModule' was not found in './core/index'
......
./~/@angular/material/dialog/index.js
21:75 export 'Platform' was not found in '../core'
Error: export 'Platform' was not found in '../core'
......

**Comment by DevVersion** [comment]
Can you guys share some code? e.g Webpack configuration and your `@NgModule`.

**Comment by fabriziodebortoli** [comment]
my app.module is very basic

```
import { MaterialModule } from '@angular/material';

@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [
    FormsModule,
    BrowserModule,
    HttpModule,
	
    MaterialModule.forRoot(),
	
    // Core module with services
    CoreModule.forRoot(),
	
    // Common components
    SharedModule,
	
    routing,
    ...
  ],
  bootstrap: [AppComponent],
  providers: [...],
  entryComponents: [...]
})
export class AppModule { }
```

and I've not a custom webpack configuration

**Comment by jelbourn** [comment]
Is this still happening with the latest version of webpack?

**Comment by Robouste** [comment]
I finally managed to upgrade webpack from beta 22 to 2.2.0-rc.3, and this is working. So yeah, problem solved with last webpack version.

**Comment by RickyGeek** [comment]
@fabriziodebortoli @davidmontgom How did you fix the problem? I still facing the 
`Uncaught TypeError: Cannot read property 'prototype' of undefined` error.
And the angular-cli is still returning the warnings:

`./~/@angular/material/module.js
64:4 export 'ProjectionModule' was not found in './core/index'
Error: export 'ProjectionModule' was not found in './core/index'
...
./~/@angular/material/dialog/index.js
21:75 export 'Platform' was not found in '../core'
Error: export 'Platform' was not found in '../core'
...`

**Comment by fabriziodebortoli** [comment]
Also with the latest version of webpack I've not fixed the issue
