### ISSUE TITLE
i expected to be above on the bottom, but shows below

### ISSUE THREAD

**Issue by patrikx3** [angular/material2#2758]
# Settings
```html
  <md-menu  y-position="above" x-position="before" #menuTheme="mdMenu">
            <button md-menu-item *ngFor="let theme of settings.themes.material"  (click)="clickChangeTheme(theme)" >
                {{ i18n.themes.material[theme] }}
            </button>
        </md-menu>
```
# Expected
To be on above.

# Bug - in image
You can see it is below.
![image](https://cloud.githubusercontent.com/assets/4770180/22186991/ecf0e1a0-e0fe-11e6-9464-8dfbbfb39356.png)

**Comment by patrikx3** [comment]
Should look always like this:
![image](https://cloud.githubusercontent.com/assets/4770180/22187018/46c0fe0e-e0ff-11e6-910e-e48666bfcdf9.png)

**Comment by patrikx3** [comment]
this happens when  after i scrolled down long page.
the menu on the footer is fixed, i scroll down, and later the menu is not positioned on the top, but going below.

**Comment by YeomansIII** [comment]
Have the same exact issue with a fixed bar along the bottom of the page. This also happens after scrolling down the page. My y-position is set to `above`.

The bug:
![screenshot at 12-29-12](https://cloud.githubusercontent.com/assets/3809115/22214972/ae502834-e167-11e6-82c7-6e7e06df20b0.png)

How it should look:
![screenshot at 12-29-28](https://cloud.githubusercontent.com/assets/3809115/22214982/b7d6ffd6-e167-11e6-95ed-0912a0fd143c.png)

**Comment by jwuliger** [comment]
Same problem here, came to see if anyone else was running into this problem.

**Comment by crisbeto** [comment]
This should've been fixed with https://github.com/angular/material2/pull/2677. Is anybody able to test against the `master` builds?

**Comment by YeomansIII** [comment]
@crisbeto Still having the issue, maybe I am getting from master wrong, this is inside my package.json:
`"@angular/material": "git+git@github.com:angular/material2.git"`

**Comment by crisbeto** [comment]
Try installing from https://github.com/angular/material2-builds @YeomansIII.

**Comment by crisbeto** [comment]
Closing in that case, thanks for testing @YeomansIII.
