### ISSUE TITLE
md-tab with ckeditor

### ISSUE THREAD

**Issue by mist3r3** [angular/material2#4734]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When adding ckeditor from ng2-ckeditor it should work

#### What is the current behavior?
I cannot render the ckeditor properly. If you put the ckeditor in the first tab it works until you change tab (and then even if you come back to the first tab the ckeditor won't work)

#### What are the steps to reproduce?
http://plnkr.co/edit/f6YoVj2cpVXTl2sAFvQy?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Ie believe there is something blocking the initialization process or something like that.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, material 2 beta 5

**Comment by tinayuangao** [comment]
Your plunker is not working. This is not a material bug.

**Comment by mist3r3** [comment]
Hi, I believe I fixed this, You need to import the divarea plugin with ckeditor. It seems this is a ckeditor bug.

**Comment by steve-todorov** [comment]
Thanks for sharing! Interestingly, using the `divarea` plugin seems to fix some of the rendering issues. However, the `unselectable` exception is still present. I've updated the [plunker](http://plnkr.co/edit/aCYY4SFCtXreiB4azR77?p=preview) demo. Is this working for you?

**Comment by mist3r3** [comment]
I do have this error but I don't know why. I'm investigating on it, if I have any news I'll share.

**Comment by steve-todorov** [comment]
For anybody who might still be affected by this issue - there is a workaround and you can check it at [md-tabs problem #124](https://github.com/chymz/ng2-ckeditor/issues/124#issuecomment-310656475)
