### ISSUE TITLE
Bug - Calendar is cutting off

### ISSUE THREAD

**Issue by avneesh123** [angular/material2#5109]
#### Bug, feature request, or proposal: 
![capture](https://user-images.githubusercontent.com/5115641/27085391-1ba71356-501d-11e7-9272-9a32a60750d5.PNG)

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
Fix already in master via https://github.com/angular/material2/pull/4696

**Comment by crisbeto** [comment]
@willshowell is correct, this is fixed in master.

**Comment by pdeveltere** [comment]
I still have this problem with the latest release.

![screen shot 2017-06-20 at 15 20 06](https://user-images.githubusercontent.com/7511273/27335229-19e37bf4-55cc-11e7-870a-bbe4313a57b3.png)
