### ISSUE TITLE
bug(docs): routing breaks on invalid url string

### ISSUE THREAD

**Issue by CaerusKaru** [angular/material2#5229]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

After navigating to incorrect route, should be able to navigate using the sidenav menu to a valid route

#### What is the current behavior?

After navigating to incorrect route, cannot navigate to any other route using the sidenav. Effectively stuck in a redirect.

#### What are the steps to reproduce?

1. Navigate to material.angular.io
2. Click on components
3. Navigate to a component using the sidenav
4. Edit the URL to change the name of a component to a clearly invalid component name
5. Try to navigate to any other part of the page using the sidenav or top navigation (the GitHub link still works, probably bc it's an absolute `href`)

#### What is the use-case or motivation for changing an existing behavior?

If someone lands on the docs page from an invalid URL, or tries to manually navigate themselves, the whole site breaks.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular Material 2.0.0-beta.7

#### Stack trace

ERROR TypeError: Cannot read property 'name' of undefined
ERROR Error: Uncaught (in promise): Error: Cannot activate an already activated outlet

**Comment by jelbourn** [comment]
Good catch, thanks

**Comment by rafaelss95** [comment]
@jelbourn I just sent a PR 2 days ago. Can you take a look at this?

**Comment by rafaelss95** [comment]
@jelbourn this issue can be closed since it's already fixed by the following PR's [angular/material.angular.io#191](https://github.com/angular/material.angular.io/pull/191) and [angular/material.angular.io#218](https://github.com/angular/material.angular.io/pull/218)

**Comment by CaerusKaru** [comment]
I don't know if this has been deployed to live yet, but in both the [staging website](https://material2-docs-dev.firebaseapp.com) and the [live site](https://material.angular.io), the issue persists with a different cause.

On improper route load:
`Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined`

Then on attempting to activate another route from sidenav:
`Error: Uncaught (in promise): Error: Outlet is not activated`

**Comment by rafaelss95** [comment]
It's another error fixed by #5667

**Comment by CaerusKaru** [comment]
Not if that merge is also live either in staging or production. cc @jelbourn

**Comment by jelbourn** [comment]
Haven't done a push yet. Closing issue for now since the fix is merged, will be applied w/ the next hosting push.
