### ISSUE TITLE
Plunkers are broken: missing components

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5245]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
See the component in plunkers

#### What is the current behavior?
I've opened the plunker for the datepicker and checkbox. These two (at least) miss the component (the selector is present, but the component itself is missing). 

![image](https://user-images.githubusercontent.com/25405143/27337788-d3817232-55a9-11e7-96c9-1bf91e8dfd31.png)

#### What are the steps to reproduce?

Open the plunkers of the docs site.

**Comment by julianobrasil** [comment]
Also there should be a section in the docs dedicated to the **expansion panel** and an update of the select section to show how to use **optionGroups**. Very nice job you've been doing!

**Comment by jelbourn** [comment]
Fixed now on material.angular.io

**Comment by yogeshgadge** [comment]
Still broken for https://material.angular.io/components/input/overview

```
Error: (SystemJS) XHR error (404) loading https://run.plnkr.co/QKIb4LQctEv9XKg1/input-hint-example.ts
	Error: XHR error (404) loading https://run.plnkr.co/QKIb4LQctEv9XKg1/input-hint-example.ts
```

**Comment by julianobrasil** [comment]
@jelbourn, just the first plunker (for basic input) is working right in input overview docs page.

**Comment by moncapitaine** [comment]
Nobody working on this? It seems there are several issues. Many older plunkers from topics on stackoverflow are broken because https://rawgit.com/angular/material2-builds isnt available any more. The material2 docs are not updated accordingly (hint: prefix changed from md to mat) etc.

Any help needed?

**Comment by vitoexe** [comment]
Why Plunkers are constantly broken?
