### ISSUE TITLE
Hide browser adressbar and menu on mobile

### ISSUE THREAD

**Issue by mackelito** [angular/material2#6637]
#### Bug, feature request, or proposal:
Not sure..

#### What is the expected behavior?
When scrolling a page the menu and adressbar should hide/minimize

#### What is the current behavior?
It stays the same when scrolling

#### What are the steps to reproduce?
Pick you fave browser (on mobile) and go to https://material.angular.io/components
Start scrolling down and you´ll see that the bar does not change.

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment]
I think this is because scrolling is done inside the `mat-sidenav-content` which the browser doesn't recognize as "scrolling the page" when it's absolutely positioned. See https://github.com/angular/material2/issues/1179

**Comment by mackelito** [comment]
Yes that was my idea as well... and we also have our menu above the `mat-sidenav-content`.. any ideas on how to solve it?

**Comment by josephperrott** [comment]
This should be resolved with #6712

**Comment by mackelito** [comment]
So this seems to still be an issue..
This ticket is about when scrolling a page.. hiding the native browser adressbar.
PR https://github.com/angular/material2/pull/6712 is about having a fixed sidenav..

Could we please reopen this?

**Comment by mackelito** [comment]
@josephperrott please reopen this as the problem still exists
