### ISSUE TITLE
Async Tabs causing Uncaught TypeError

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/material2#695]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
No error

#### What is the current behavior?
zone.js:260 Uncaught TypeError: Cannot read property 'elementRef' of undefined

#### What are the steps to reproduce?
Installed:

    "@angular2-material/core": "^2.0.0-alpha.5-2",
    "@angular2-material/input": "^2.0.0-alpha.5-2",
    "@angular2-material/tabs": "^2.0.0-alpha.5-2",
    "@angular2-material/toolbar": "^2.0.0-alpha.5-2",

Using this template:
https://github.com/angular/material2/blob/master/src/demo-app/tabs/tab-group-demo.html

Console reads:
Uncaught TypeError: Cannot read property 'elementRef' of undefined
zone.js:260

#### What is the use-case or motivation for changing an existing behavior?
Errors should not be showing in the console

#### Which versions of Angular, Material, OS, browsers are affected?
Angular RC1, Material 2.0.0-alpha.5-2, All browsers seem to be affected as I tested in both Chrome and Microsoft Edge

#### Is there anything else we should know?
Tabs still are functional just the error makes it less appealing to use the async function.

**Comment by jelbourn** [comment]
@robertmesserle take a look?

**Comment by robertmesserle** [comment]
@jelbourn This should have been fixed by https://github.com/angular/material2/commit/231467d22f4ba1108399faf56330b09ca78300b1

Do you know if alpha.5-2 includes it?  (This commit was 10 days ago, not sure when 5-2 was released.)

**Comment by robertmesserle** [comment]
Ah, found the commit for 5-2.  This is fixed already and will be included in the next release.

**Comment by RicardoVaranda** [comment]
Hey guys, has this issue been addressed yet. I'm still getting it on alpha 6
