### ISSUE TITLE
md-select inside md-dialog does out of dialog DOM so, bottom value in inline style is calculated wrong that disapper the select

### ISSUE THREAD

**Issue by ervbsankar** [angular/material2#7137]
#### Bug, feature request, or proposal:
md-select or md-datepicker does out of DOM so, it is not positioned correctly inside md-dialog

#### What is the expected behavior?
md-select or md-datepicker should allign with md-dialog DOM

#### What is the current behavior?
md-select or md-datepicker does out of DOM so, it is not positioned correctly inside md-dialog

#### What are the steps to reproduce?
this is user search web page
1.  main page of UI have search results from search button with name as search criteria
2. there is button next to search button that open dialog to add new users
3. this dialog have date of birth date picker and select to select male/female
4. bottom css is calculated automatically in cdk-overlay-1 that moves the select towards top

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
 "@angular/animations": "^4.3.3",
    "@angular/cdk": "^2.0.0-beta.8",
 "@angular/material": "^2.0.0-beta.8",
grome broswer

**Comment by ervbsankar** [comment]
`<div id="cdk-overlay-3" class="cdk-overlay-pane" dir="ltr" style="pointer-events: auto;/* bottom: 190.5px; */left: 476px;"><md-datepicker-content class="mat-datepicker-content"><div tabindex="0" class="cdk-visually-hidden cdk-focus-trap-anchor"></div><md-calendar cdktrapfocus="" class="mat-calendar" id="md-datepicker-1"><div class="mat-calendar-header"><div class="mat-calendar-controls"><!----><button class="mat-calendar-period-button mat-button" md-button="" aria-label="Change to year view"><span class="mat-button-wrapper">SEP 2017<div class="mat-calendar-arrow"></div></span><div class="mat-button-ripple mat-ripple" md-ripple=""></div><div class="mat-button-focus-overlay"></div></button> <!----><div class="mat-calendar-spacer"></div><!----><button class="mat-calendar-previous-button mat-icon-button" md-icon-button="" aria-label="Previous month"><span class="mat-button-wrapper"></span><div class="mat-button-ripple mat-ripple mat-button-ripple-round" md-ripple=""></div><div class="mat-button-focus-overlay"></div></button> <!----> <!----><button class="mat-calendar-next-button mat-icon-button" md-icon-button="" aria-label="Next month"><span class="mat-button-wrapper"></span><div class="mat-button-ripple mat-ripple mat-button-ripple-round" md-ripple=""></div><div class="mat-button-focus-overlay"></div></button> <!----></div></div><div cdkmonitorsubtreefocus="" class="mat-calendar-content"><!----><md-month-view><table class="mat-calendar-table"><thead class="mat-calendar-table-header"><tr><!----><th aria-label="Sunday">S</th><th aria-label="Monday">M</th><th aria-label="Tuesday">T</th><th aria-label="Wednesday">W</th><th aria-label="Thursday">T</th><th aria-label="Friday">F</th><th aria-label="Saturday">S</th></tr><tr><th aria-hidden="true" class="mat-calendar-table-header-divider" colspan="7"></th></tr></thead><tbody class="mat-calendar-body" md-calendar-body="" role="grid"><!----><!----><tr role="row"><!----><td aria-hidden="true" class="mat-calendar-body-label" colspan="5" style="padding-top: 7.14286%; padding-bottom: 7.14286%;">SEP</td><!----><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 1, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">1</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 2, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">2</div></td></tr><tr role="row"><!----><!----><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 3, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">3</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 4, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">4</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 5, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">5</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 6, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">6</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 7, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">7</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 8, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">8</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 9, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">9</div></td></tr><tr role="row"><!----><!----><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 10, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">10</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 11, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">11</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 12, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">12</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 13, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">13</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 14, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">14</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 15, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">15</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 16, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">16</div></td></tr><tr role="row"><!----><!----><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 17, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">17</div></td><td class="mat-calendar-body-cell mat-calendar-body-active" role="gridcell" tabindex="0" aria-label="September 18, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content mat-calendar-body-today">18</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 19, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">19</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 20, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">20</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 21, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">21</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 22, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">22</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 23, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">23</div></td></tr><tr role="row"><!----><!----><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 24, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">24</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 25, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">25</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 26, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">26</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 27, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">27</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 28, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">28</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 29, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">29</div></td><td class="mat-calendar-body-cell" role="gridcell" tabindex="-1" aria-label="September 30, 2017" style="width: 14.2857%; padding-top: 7.14286%; padding-bottom: 7.14286%;"><div class="mat-calendar-body-cell-content">30</div></td></tr></tbody></table></md-month-view><!----></div></md-calendar><div tabindex="0" class="cdk-visually-hidden cdk-focus-trap-anchor"></div></md-datepicker-content></div>`

**Comment by julianobrasil** [comment]
Have you tried beta.10? I should have been fixed in #4696 (may/2017). Could you provide a plunker?

Also:

> this is user search web page

where is this _search web page_? Provide a link.

**Comment by ervbsankar** [comment]
i have tried beta.10, it is still happening, i will try to send you a plunk

**Comment by ervbsankar** [comment]
<img width="1280" alt="screen shot 2017-09-18 at 11 33 57 am" src="https://user-images.githubusercontent.com/10236592/30552956-4fee3cd6-9c65-11e7-9ad7-dfc1e6daa333.png">

**Comment by ervbsankar** [comment]
<img width="1280" alt="screen shot 2017-09-18 at 11 36 35 am" src="https://user-images.githubusercontent.com/10236592/30553076-a60c9554-9c65-11e7-8ed0-97c86e1fbf0a.png">

**Comment by ervbsankar** [comment]
please see the screenshot, Date picker is not opening because bottom value in style is pushing the date picker towards up.

I still feel it is a defect

**Comment by ervbsankar** [comment]
removing the bottom value in style after inspecting it is showing the date picker. Please see below picture

<img width="1280" alt="screen shot 2017-09-18 at 11 40 23 am" src="https://user-images.githubusercontent.com/10236592/30553250-3bc2938c-9c66-11e7-990a-8dd78b0c9e5d.png">

**Comment by crisbeto** [comment]
I couldn't reproduce it purely by putting a datepicker inside a dialog. Can you post a Plunkr showing the issue?

**Comment by julianobrasil** [comment]
@ervbsankar, are you doing something that potentially change css, like dynamically changing the app's theme?

**Comment by ervbsankar** [comment]
when it is 80% it is showing the date picker. please see below picture
<img width="1280" alt="screen shot 2017-09-18 at 3 55 38 pm" src="https://user-images.githubusercontent.com/10236592/30564224-f796ff6c-9c89-11e7-9bb0-6462ff369627.png">

**Comment by julianobrasil** [comment]
It seems to be something in your project. It is not related to datepicker inside dialogs nor with lack of screen space (see the picture bellow, that, even without space, the calendar popup is visible). Here is a plunk (try to reproduce the problem you're facing): https://plnkr.co/edit/4mtNqOcxCynrw4UmrnrG?p=preview

![image](https://user-images.githubusercontent.com/25405143/30564916-ec96e5d8-9c9c-11e7-9cbb-366ffe090bf3.png)

**Comment by ervbsankar** [comment]
It is not with CSS, after figuring out, I found that
removing height value (height: '500px') in below line, brought the date picker to position correctly. 
 this.modalRef =  this.modalService.open(CustomDialogComponent,{width: '400px',});

Please let me know how to set the height of Dialog.

**Comment by julianobrasil** [comment]
```js
this.modalRef = this.modalService.open(CustomDialogComponent,{width: '400px',height:'400px'});
```

**Comment by ervbsankar** [comment]
setting value to height is making date picker or Options go disappear.

**Comment by ervbsankar** [comment]
it is happening with ngx-bootstrap modal too.  date and select of angular materials are moving towards top of the screen and
this popup of date and select of angular materials showing behind of ngx-bootstrap modal.

**Comment by josephperrott** [comment]
Unfortunately without providing a reproduction case it is not possible for us to troubleshoot the bug and fix it.  If you can provide a reproduction case we can go from there:

[Here](https://plnkr.co/edit/eURdN8Reo6th1YQifXZ7?p=preview) is a plunkr that has the situation you described.  If you can reproduce the issue from here we can take a look.

**Comment by jelbourn** [comment]
We haven't been able to reproduce this issue. Feel free to open a new issue if you are able to provide a reproduction via StackBlitz.
