### ISSUE TITLE
Documentation needs to show version information, careful cache policy

### ISSUE THREAD

**Issue by thw0rted** [angular/material2#7660]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Visiting a page under the official docs (e.g. `https://material.angular.io/components/tabs/overview`) should a) show the latest information about a component and b) tell you what version / release it applies to somewhere on the page.

#### What is the current behavior?

The page says nothing about what version it applies to.  **Critically**, the page is aggressively cached, so unless a user force-refreshes the page, they may be looking at old versions of the docs that reference directives / parameters / whatever that don't exist anymore or have changed.  I'm not sure how the "Edit in Plunker" link works under the hood but somehow the old page links to an older version of the Plunker that includes older code syntax, which *does not work* against the current build of the library.  The end result is that users will find that examples (appear to) just [mysteriously stop working one day](https://plnkr.co/group?place=msg%2Fplunker%2FdMYovdyR9bM%2FLEAdizMFBgAJ).

#### What are the steps to reproduce?

Open all the pages in the documentation, then wait until a major revision changes a bunch of syntax, then go back to the page and find that it reflects the old syntax, with links to examples that are also still written in the old syntax.

#### What is the use-case or motivation for changing an existing behavior?

I would like to *not* waste an entire day trying to figure out "why all these Plunkers broke out of the blue".

#### Is there anything else we should know?

The examples don't link a specific version of Angular or Material in their `systemjs.config.js`, e.g.:

>     '@angular/material': 'https://unpkg.com/@angular/material/bundles/material.umd.js',

This means that old examples will blithely load the new version of the code and just stop working.  All examples should use a config file that points to a specific version of all dependencies, but *especially* the dependency they're trying to demonstrate (i.e. Material).

**Comment by willshowell** [comment]
Having the version listed on the page is [here](https://github.com/angular/material.angular.io/pull/246), but I agree, there really should be some cache-busting technique for the assets (related https://github.com/angular/material2/issues/7629).

I also strongly agree with the [plunker-writer](https://github.com/angular/material.angular.io/blob/master/src/app/shared/plunker/plunker-writer.ts) (and plunker template) pinning the version [like core's template does](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Comment by andrewseguin** [comment]
I've had issue with this as well, especially with the change from `md` to `mat`. I see the `md` docs still on many of my browser sessions, and I need to force-refresh just to get the new stuff.

**Comment by fad250** [comment]
@andrewseguin Thanks for mentioning this. I found the documentation very confusing. I didn't even realize I had to force refresh to get the new changes.

**Comment by thw0rted** [comment]
It's been a month and now all the Plunkers are broken again.  [Users are confused](https://stackoverflow.com/questions/43320622/not-able-to-run-angular-2-material-plunker-example), no surprise there.  Do we need a separate issue for "all example code / Plunker templates must link to specific versions of every dependency"?  They're just going to break every month or two otherwise...

**Comment by jelbourn** [comment]
Closing this since, AFAIK, this should now be resolved (SW cache should no longer become super stale).

**Comment by thw0rted** [comment]
I'm glad the caching problem is fixed.  Should I open separate issues for the other stuff?

* Docs should show version number (pull request is still open)
* `material.angular.io` should host historical versions of docs (does Material2 have a stated support lifecycle? If so, all supported versions need online docs)
* documentation examples should link to specific versions of dependencies on unpkg instead of inheriting latest (required for above to actually be practical)

**Comment by jelbourn** [comment]
Major versions will persist in the docs (e.g., once 6.0 comes out, the docs for 5.0 will still be available). 

Feel free to file an issue for the stackblitz versions

**Comment by pantonis** [comment]
I am still having this issue with cached version. Opening the material documentation in chrome shows a very old version. In firefox I get latest documentation. Even If I do force refresh CTRL + F5 I still see old version of documentation in chrome
