### ISSUE TITLE
md-option [value] is not part of component

### ISSUE THREAD

**Issue by BenoitDelrue** [angular/material2#7705]
Can't bind to 'value' since it isn't a known property of 'md-option' for material@2.0.0-beta.12

The official plunker for md-select is also not working anymore :
https://plnkr.co/edit/NB387exfVg0Cptr3tcZZ?p=preview

**Comment by benb7760** [comment]
[md -> mat](https://github.com/angular/material2/blob/master/CHANGELOG.md#deprecation-of-md-prefix)

**Comment by crisbeto** [comment]
It should be resolved if you switch to the `mat-` prefix. [See the beta.11 changelog.](https://github.com/angular/material2/tree/2.0.0-beta.11)

**Comment by tomchovanec** [comment]
When I've switched to mat-*, I still get: 

zone.js?6524:196 Uncaught Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'mat-option'.
1. If 'mat-option' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'mat-option' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (")">
        <mat-option>Not selected</mat-option>
        <mat-option *ngFor="let report of reports" [ERROR ->][value]="report">{{report.name}}</mat-option>
    </mat-select>

**Comment by avilao** [comment]
I also get this error.

**Comment by afmesag** [comment]
I also had that problem, I forgot to import the module 'MatSelectModule' in the app.module.ts.

**Comment by aldari** [comment]
Hi, I confirm this message appear without
import { MatSelectModule } from '@angular/material/select'; 
in app.module
and MatSelectModule in import.
Close the ticket

I have no a collection and use alternative syntax
`<mat-radio-group name="gender" [(ngModel)]="gender">
  <mat-radio-button value="0">
	Male
  </mat-radio-button>
  <mat-radio-button value="1">
	Female
  </mat-radio-button>
</mat-radio-group>`

**Comment by jh3141** [comment]
Of course, if you're seeing the error in unit tests, you may also need to import the module in your spec.ts file, as well as app.module.ts ... and for anyone like me still using beta 10 (updating existing apps seems to be quite a bit of work) the relevant module name is of course `MdSelectModule`.

**Comment by roh1tgupta** [comment]
i also got stuck there...u guys saved my time..thanks!!

**Comment by clement911** [comment]
What is this not documented though? No mention on https://material.angular.io/components/select/overview ?
