### ISSUE TITLE
Allow @angular/core ^5.0.0 and 5.0.0-rc.* as peer dependencies of material and cdk

### ISSUE THREAD

**Issue by IgorMinar** [angular/material2#7780]
#### Bug, feature request, or proposal:

We know that the latest versions of material and cdk are compatible with the latest `@next` version of Angular because that's what we use at Google. We should therefore  configure the peer dependencies of the npm packages to support both the `@lastest` as well as `@next` version.

#### What is the expected behavior?
No installation warnings from npm/yarn

#### What is the current behavior?
```
warning "@angular/cdk@2.0.0-beta.12" has incorrect peer dependency "@angular/core@~4.4.4".
warning "@angular/cdk@2.0.0-beta.12" has incorrect peer dependency "@angular/common@~4.4.4".
warning "@angular/material@2.0.0-beta.12" has incorrect peer dependency "@angular/core@~4.4.4".
warning "@angular/material@2.0.0-beta.12" has incorrect peer dependency "@angular/common@~4.4.4".

```

**Comment by pfeigl** [comment]
Angular 5 has now been released, so this affects quite alot of people now. 

Running a simple "ng new" and "yarn add @angular/material" directly puts one into this situation.
Are there already any plans to get this addressed?

**Comment by willshowell** [comment]
@pfeigl I believe it has been addressed in #6018 and #8177 and will be available in the next release.

**Comment by jelbourn** [comment]
There will be a release on Monday that resolves this.

**Comment by aklauza** [comment]
That's great, thanks!

**Comment by radoslavpetranov** [comment]
Awesome news! Thanks for handing this so quickly guys!

**Comment by sulimanfarzat** [comment]
no work with me too

npm WARN @angular/cdk@5.0.0-rc0 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by WilliamAllworth** [comment]
I'm running 
node v6.11.1
npm v3.10.10

I ran the following commands on osx
npm install -g @angular/cli
ng new my-app
cd my-app
npm install --save @angular/material @angular/cdk

xxxxxxxxxxx@0.0.0 /Users/xxxxxxxxxxx/projects/xxxx/xxxxxxxxx
├── @angular/cdk@5.0.0-rc0 
├── UNMET PEER DEPENDENCY @angular/compiler@5.0.0
├── UNMET PEER DEPENDENCY @angular/core@5.0.0
└── @angular/material@5.0.0-rc0 

npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.

**Comment by tgambet** [comment]
@WilliamAllworth : For the warnings you can update codelyzer manually to version 4.0.1 in package.json

**Comment by jelbourn** [comment]
This was resolved with rc0

**Comment by Thorski** [comment]
How do I get the fix, I still get this with rc.1
new project (ng new)
npm: 5.5.1
Angular CLI: 1.5.3
Node: 8.9.0
@angular/cdk: 5.0.0-rc.1
@angular/cli: 1.5.3
@angular/material: 5.0.0-rc.1

npm ERR! peer dep missing: @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0, required by codelyzer@3.2.2
npm ERR! peer dep missing: @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0, required by codelyzer@3.2.2

**Comment by IgorMinar** [comment]
The old peer dep requirement is coming from codelyzer. Please update to the
latest version and it that doesn't help file an issue for codelyzer to
update the dep.
