### ISSUE TITLE
bug(rc5 and alpha7)url_resolver.js:238Uncaught TypeError: uri.match is not a function

### ISSUE THREAD

**Issue by qdouble** [angular/material2#974]
I'm refiling for this issue: https://github.com/angular/material2/issues/963 as it was not resolved in alpha 7. I've tested it on two fresh seed projects and the error still occurs, so it should be a common problem with Webpack at least, not sure if this shows up in a SystemJS build or not.

**Comment by FoodBuster** [comment]
I second this. Having the same problem, using the new angular-cli webpack release.

**Comment by qdouble** [comment]
This seems to be related to the moduleId how it's dealing with the moduleId, if you comment out the moduleId of the components, they compile without error.

**Comment by qdouble** [comment]
It appears this pull request will pull this issue https://github.com/angular/angular/pull/10595/commits/f54f9efc0e70eb1c71ac8eb6a8ed690f1e7f09f9. You guys can close this if you want to as it appears to be an angular compiler issue and not specific to material

**Comment by FoodBuster** [comment]
qdouble, that pull request does fix the "TypeError: uri.match is not a function" problem, but gives me a BaseException error with the following message: 

`Template parse errors:↵Can't bind to 'md-ripple-trigger' since it isn't a known property of 'div'. ("*ngIf="isRippleEnabled()" class="md-button-ripple" [class.md-button-ripple-round]="isRoundButton()" [ERROR ->][md-ripple-trigger]="getHostElement()" [md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)"): MdButton@0:180↵Can't bind to 'md-ripple-color' since it isn't a known property of 'div'. ("ton-ripple" [class.md-button-ripple-round]="isRoundButton()" [md-ripple-trigger]="getHostElement()" [ERROR ->][md-ripple-color]="isRoundButton() ? 'rgba(255, 255, 255, 0.2)' : ''" md-ripple-background-color="rgb"): MdButton@0:219`

If this is an angular-cli-specific issue, happy to take it up there.

**Comment by qdouble** [comment]
@FoodBuster that's an unrelated error, it saying 'md-ripple-trigger' isn't defined on the MdButton directive/component.

**Comment by FoodBuster** [comment]
@qdouble Thanks, got it working.

**Comment by jelbourn** [comment]
I have released an `alpha.7-2` that _should_ fix this.

**Comment by zigzag95** [comment]
Thanks

**Comment by neclepsio** [comment]
Maybe I'm doing something wrong, but simply upgrading to alpha.7-2 doesn't fix for me.

**Comment by qdouble** [comment]
@neclepsio it's possible another component or 3rd party plugin in your application has a moduleId.

**Comment by neclepsio** [comment]
@qdouble I don't think so. I'm just using BrowserModule, FormsModule and several Ms...Module. How can I check? Thank you.

**Comment by neclepsio** [comment]
@qdouble You were right! My own app.component had a moduleId!

**Comment by zackporter92** [comment]
@jelbourn Your fix in alpha.7-2 works for me, but it appears the problem was reintroduced somewhere before alpha.7-9.  Can you try to fix it in again?

**Comment by qdouble** [comment]
@zackporter92 this caused it to pop back up: https://github.com/angular/material2/pull/1101

**Comment by zackporter92** [comment]
@qdouble interesting. So we should just stick to 7-2 if we have that problem?

**Comment by qdouble** [comment]
For temporary workaround, you can put this as a preloader in your webpack config, just npm install string-replace-loader
```
preLoaders: [
      {
        test: /.js$/,
        loader: 'string-replace-loader',
        query: {
          search: 'moduleId: module.id,',
          replace: '',
          flags: 'g'
        }
      },
```

or on @angular/compiler/src/url_resolver.js line 238, you can change 
`return uri.match(_splitRe);` to `return uri.toString().match(_splitRe);`

**Comment by DerejeKitaw** [comment]
I get same error. I am using final release Angular2. 
"Uncaught TypeError: uri.match is not a function"

It work when I remove "moduleId: module.id" from [contact component](https://github.com/DerejeKitaw/module/blob/master/src/app/contact/contact.component.ts).
